### ISSUE TITLE
Actual compile support

### ISSUE THREAD

**Issue by Lazerbeak12345** [racket/rhombus-brainstorming#191]
One of my biggest problems I've had with racket is that it doesn't have an option to compile. The benefits would be:

- ease of distribution of production software built on the racket framework
- speed
- perhaps size? (the presence of `eval` might mean that significant parts of the code pipeline would need to be bundled)

It _is_ worth noting that when using `raco exe` it does convert to a binary format (as do a few other commands), but if you dig into this exe (in my case a linux binary), it is not standalone, and is actually not even a binary in the usual sense.

**Comment by Lazerbeak12345** [comment]
Interesting thoughts about Chez Scheme and compiled binaries: https://stackoverflow.com/questions/48061220/can-chez-scheme-produce-compiled-binaries

**Comment by Lazerbeak12345** [comment]
Linked in that article is this tool: https://github.com/gwatt/chez-exe

**Comment by spdegabrielle** [comment]
Hi @Lazerbeak12345 
Racket uses the same incremental native-code compiler as Chez Scheme. The ‘CS’ compiler has been the default compiler since version 8.0.  (8.3 was just released )

> In interactive mode, this compilation occurs automatically and on-the-fly. Tools like raco make and raco setup marshal compiled bytecode to a file, so that you do not have to compile from source every time that you run a program. See Compilation and Configuration: raco for more information on generating bytecode files.

> For the CS implementation of Racket, the main bytecode format is non-portable machine code.

Racket Reference, 19  19 Performance: [19.3 Bytecode, Machine Code, and Just-in-Time (JIT) Compilers](https://docs.racket-lang.org/guide/performance.html#%28part._.J.I.T%29)

There is a small sample with instructions to create a stand-alone executable at https://github.com/racket-templates/cli-command

I hope this helps
Best wishes
Stephen

**Comment by LiberalArtist** [comment]
I think the part you're missing is probably [`raco distribute`: Sharing Stand-Alone Executables](https://docs.racket-lang.org/raco/exe-dist.html). In particular, this advice may be relevant:
> The number of needed support files depends in part on the way that executables for a distribution are created. Supplying `--embed-dlls` or `--orig-exe` to `raco exe` reduces the need for support files, but at the expense of making the distribution larger if it contains multiple executables.
